" --- Basic functionalities
set ruler
set number
set nocompatible
set backspace=start,eol,indent
filetype off


" --- Vundle plugins management
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Bundle 'gmarik/Vundle.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'scrooloose/nerdtree'
Bundle 'klen/python-mode'
Bundle 'majutsushi/tagbar'
Bundle 'altercation/vim-colors-solarized'
Bundle 'vim-scripts/closetag.vim'
Bundle 'phleet/vim-mercenary'
Bundle 'leafgarland/typescript-vim'
Bundle 'fatih/vim-go'

call vundle#end()


" --- Filetype plugin
filetype plugin indent on


" --- Search options
set incsearch
set hlsearch


" --- Indentation options ---
set autoindent
set smartindent
set showmatch
set smarttab
set tabstop=4
set shiftwidth=4
set expandtab

" For selected files like HTML, JavaScript or YAML, 2 spaces
autocmd Filetype html,css,javascript,typescript,yaml,yml setlocal ts=2 sw=2 expandtab

" Python smart indentation definitions
autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class


" --- Code folding
" This allows you to be inside a method and type 'za' to open and close a fold
" (in command mode, of course).
set foldmethod=indent
set foldlevel=99


" --- General key mapping

" Tab navigation mapping. You can now press F8 to change to the left tab and
" F9 to change to the right tab.
map <silent> <F8> :tabp<CR>
map <silent> <F9> :tabn<CR>

" Tagbar plugin activation.
map <C-t> :TagbarToggle<CR>


" --- NERDTree configuration

" Automatically load NERDTree when Vim starts without any loaded file.
autocmd vimenter * if !argc() | NERDTree | endif

" Close Vim if the only opened window is NERDTree.
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Map 'Ctrl+n' to open NERDTree.
map <C-n> :NERDTreeToggle<CR>


" --- Syntax highlighting ---
syntax enable
set background=dark

if !has('gui_running')
    set t_Co=256
    let g:solarized_termcolors=256
    let g:solarized_termtrans=1
else
    " --- Deactivate Rope due to heaviness while working with Vim GUIs ---
    let g:pymode_rope = 0
endif

colorscheme solarized


" --- HTML automatic tag closing ---
autocmd Filetype html,xml,xsl source ~/.vim/bundle/closetag.vim/plugin/closetag.vim 
let g:closetag_html_style=1


" --- NERDTree ignores ---
let NERDTreeIgnore = ['\.pyc$']
